language: php

services:
  - mysql
  
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
env:
#  - SYMFONY_VERSION=2.6.*
#  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=dev-master

before_install:
  - mysql -e 'create database hotel1_test;'
  
before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer require symfony/symfony:${SYMFONY_VERSION}
#  - composer install
  - php app/console doctrine:schema:create --env=test
  - php app/console doctrine:fixtures:load -n --env=test

script:
  - phpunit -c app

notifications:
  email: tarviz@listy.internetowe.pl
  
matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - env: SYMFONY_VERSION=2.6.*
    - env: SYMFONY_VERSION=2.7.*
    - php: 5.5
    - php: hhvm
