<?php

namespace AppBundle\Entity\Repository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends \Doctrine\ORM\EntityRepository
{

    public function getRoomsReservedOn($reservarionDay)
    {
        $qb = $this->createQueryBuilder('a')
        ->select([
            'Reservation',
            'Room'
        ])
        ->from('AppBundle\Entity\Reservation', 'Reservation')
        ->leftJoin('Reservation.resource', 'Room')
        ->where("Reservation.day = :day")
        ->setParameter('day', $reservarionDay);
        ///->addOrderBy('Reservation.name', 'ASC')
        //
        
        return $qb->getQuery()->getResult();
        
    }
    
    public function getRoomsAvailabilitiesOn($reservarionDay)
    {
        $qb = $this->createQueryBuilder('a')
        ->select([
            'Room',
            'Reservation',
        ])
        ->from('AppBundle\Entity\Reservation', 'Reservation')
        ->leftJoin('Reservation.resource', 'Room')
        //->where("Reservation.day = :day")
        //->setParameter('day', $reservarionDay)
        ///->addOrderBy('Reservation.name', 'ASC')
        //
        ;
        return $qb->getQuery()->getResult();
    
    }
}
