<?php

namespace AppBundle\Entity\Repository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends \Doctrine\ORM\EntityRepository
{

    public function getRoomsReservedOn($reservarionDay)
    {
        $qb = $this->createQueryBuilder('a')
        ->select([
            'Reservation',
            'Room'
        ])
        ->from('AppBundle\Entity\Reservation', 'Reservation')
        ->leftJoin('Reservation.resource', 'Room')
        ->where("Reservation.day = :day")
        ->setParameter('day', $reservarionDay);
        ///->addOrderBy('Reservation.name', 'ASC')
        //
        
        return $qb->getQuery()->getResult();
        
    }
    

    /**
     * Zwraca wolne pokoje danego dnia
     * @param date $day
     */
    public function getFreeRooms($day)
    {
        $qb = $this->createQueryBuilder('b')
        ->select('Room')
        ->from('AppBundle:Room', 'Room')
        ->where('Room NOT IN (
                    SELECT Res.id
                    FROM AppBundle:Reservation Rez,
                    AppBundle:Resource Res
                    WHERE DATE_DIFF(Rez.day, :day)<1 AND Rez.resource = Res
                )')
                    ->setParameter('day', $day)
                    ->addOrderBy('Room.name', 'ASC');
    
                    return  $qb->getQuery()->getResult();
    }
    
    public function getRoomsAvailabilitiesOn($reservarionDay)
    {
        $qb = $this->createQueryBuilder('a')
        ->select([
            'Room',
            'Reservation',
        ])
        ->from('AppBundle\Entity\Reservation', 'Reservation')
        ->leftJoin('Reservation.resource', 'Room')
        //->where("Reservation.day = :day")
        //->setParameter('day', $reservarionDay)
        ///->addOrderBy('Reservation.name', 'ASC')
        //
        ;
        return $qb->getQuery()->getResult();
    
    }
}
